# prowl-github-app configuration. Place in default branch

version: '0.1.0'

pull_requests:
  - id: catchall
    include:
      - "**/*"
    base:
      - master
    merge: squash
    reviewers:
      - tommilligan
    approve_methods:
      - comment
      - review
  - id: markdown
    include:
      - "**/*.md"
    base:
      - master
    merge: squash
    reviewers: []
    approve_methods:
      - comment
      - review

